homebrew-build/build-darwin.sh

Added a `chmod 755` to the script that assembles the macOS tar.gz file to make the appsody controller executable.

Made controller executable on macOS

---

cmd/deploy.go
cmd/utils.go
cmd/utils_test.go

This updates `appsody deploy` so that the local Docker cache will be used if the `--push` option is not provided.
To do this, the image must be tagged as `dev.local/<name>`, and the `ImagePullPolicy` needs to be something other than `Always`.

Local deploy

---

build.md

Currently the CLI fails to build if the version
is lower than 1.12.  Specify that level as one
of the pre-reqs.

doc: specify the minimum go version

---

.travis.yml
cmd/build.go
cmd/deploy.go
cmd/utils.go

`appsody build` would fail if the project directory has capital letters in it. This happens because Appsody uses the folder name as the image name to build. Since Docker doesn't support capital letters, `appsody build` fails in these circumstances.
The current PR introduces two main changes:
1) In case you run `appsody build` with no flags, the project name is lowercased and used as the image name.
2) There's a new `-t <tag>` flag that you can use to specify an arbitrary tag name. If you use this flag, you shouldn't be using capital letters in the tag (we'll just pass it on to Docker as is). 
Now - these changes (and this issue) have some repercussions on `appsody deploy` as well. This command has two flags:
1) `-t <tag>` which is passed on to the `appsody build` command if it is present …

Allow appsody to build projects with capital letters in their folder name

---

cmd/root.go

root.go: fixed config file path

---

.travis.yml
cmd/repo.go

Modified the transport creation in repo.go to include the http(s) proxy from the environment.
Now - clients who set the HTTPS_PROXY or HTTP_PROXY env var will go through the proxy.
This fixes #90.

Http proxy fix

---

.travis.yml
cmd/extract.go
cmd/utils.go

Caught os.Rename() error and added logic to copy dirs and their contents.
Tested with java-microprofile on both Windows (C:\ and D:\ drives) and Linux (multiple disks). 
This fixes #82.

Adding support for multiple disk devices

---

.travis.yml
Makefile
cmd/dev_common.go

This PR addresses #100, by removing the check on the presence of an `appsody-controller` file in the $HOME/.appsody directory. Now, the CLI always copies the controller from the binary directory, ensuring that the user is working with the correct level of the controller, even after an upgrade of the CLI.
One ramification of this change is that it broke the automated tests. Therefore, we had to pass the `APPSODY_MOUNT_CONTROLLER` env var to the `go test` commands for full and functional testing, so that the copy would be skipped in test mode.

Ensure CLI always updates the appsody-controller

---

.travis.yml
cmd/extract.go

Mixed case still present in the project extract directory, which causes issues on Linux (but not on Mac or Windows, where Docker seems to be tolerant of mixed case in paths). 
Fixes https://github.com/eclipse/codewind/issues/33.
Fixes #107

CLI Extract: project directory mixed case fix

---

Gopkg.lock
cmd/repo.go
cmd/repo_add.go
cmd/root.go
vendor/github.com/pkg/errors/.gitignore
vendor/github.com/pkg/errors/.travis.yml
vendor/github.com/pkg/errors/LICENSE
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/appveyor.yml
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/stack.go

In partial fulfillment of #36 
Removes os.exit from repo_add.go
Silences error and usage on root.go
Temporary logging fix for line numbers.

os.Exit #1 for repo add

---

cmd/debug.go
cmd/dev_common.go
cmd/docs.go
cmd/list.go
cmd/repo_remove.go
cmd/repo_remove_test.go
cmd/run.go
cmd/test.go

Partial fulfillment of #36 
Removes os.exit from appsody run, appsody debug, appsody test paths

Remove os.exit from Run path of appsody run, appsody debug, and appsody test

---

.travis.yml
cmd/utils.go

The CLI was using the incorrect flag for `--namespace` in the `kubectl` command. Replaced the incorrect `--name` flag with `--namespace`.
Fixes #109

CLI deploy: handle namespace flag appropriately

---

cmd/build.go
cmd/build_delete.go
cmd/build_setup.go
cmd/deploy.go

Partial fulfillment of #36 
Removed os.exit from build.go, deploy.go, build_setup.go, build_delete.go

removed os.exit from build and deploy commands

---

cmd/build.go
cmd/extract.go
cmd/init.go

Partial fulfillment of #36 
Removed os.exit from extract.go
Changed init.go and build.go to use extractCmd.RunE.

removed os.exit(1) from extract

---

cmd/build.go
cmd/deploy.go
cmd/dev_common.go
cmd/extract.go
cmd/init.go
cmd/run.go
cmd/stop.go
cmd/utils.go

Partial fullfillment of #36 
Removed os.exit calls from utils.go and callers of utils.go

Remove os exit from utils.go and parent callers

---

.travis.yml
cmd/init.go
cmd/list.go
cmd/repo.go
cmd/repo_remove.go

This PR introduces the following functionality:
1) Supports multiple repositories in an adequate way. Now, the same stack name may be present in multiple repositories.
1) Introduces the concept of *default repo*. The default repo is marked with an asterisk when you run `appsody repo list`. The default repo can be modified by manually editing `~/.appsody/repository/repository.yaml` and moving the `default:true` yaml element to the repo that you want to make the default repo.
1) Now, `appsody list` lists all the stacks that are available with an indication of the repo they come from.
1) There's a new `appsody list <repo>` variation of the command, which only shows the stacks in the specified repo (if it exists).
1) To create an appsody project, you can keep using the old `appsody init …

Added initial support for multiple repos

---

.travis.yml
cmd/init.go
cmd/repo.go

This PR allows the CLI to deal with a mixture of V1 and V2 repositories.

CLI repo and init: add support for V2 repository schema

---

cmd/dev_common.go

Adds an if check so we don't print out an Error <nil> message on a good Ctrl-c for appsody run, etc.
Fulfills #142

additional check for error message

---

.travis.yml
cmd/init.go
cmd/repo.go
cmd/repo_list.go
cmd/repo_remove.go

"Legacy" CLI users (i.e. 0.2.8 and prior) may not have a default repo. This PR sets the default repo to either the only one they may have, or "appsodyhub" if it's there, or the first one in their list if they have multiple repos and no "appsodyhub".
Also handles situations in which the repo that's specified in requests isn't found.

Handling missing default repo and situations where repo not found

---

RELEASE.md
win-build/build-win.sh

Fixes #132 
Changes Windows archieve file name from ".tar" to ".tar.gz" extension.

Added .gz to the windows archieve file name, updated RELEASE.md

---

cmd/repo.go

Fixes #159 
Changed the URL to 
"https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml"

Changed default index.yaml URL

---

cmd/utils.go

The Appsody CLI config in `$HOME/.`appsody/.appsody.yaml` provides an `images` field to allow for custom image repositories for the Appsody Stack Images:
```
$ cat ~/.appsody/.appsody.yaml 
home: /Users/bailey/.appsody
images: index.docker.io
tektonserver: ""
```
The `images` field isn't currently honoured. This updates the CLI so that if that field is set to anything other that `index.docker.io` (ie, DockerHub), it uses that repo to find the Appsody Stack Images.

Add support for custom image repositories for stacks

---

cmd/extract.go
cmd/utils.go

The `appsody extract` and therefore `appsody build` commands currently make the assumption that the application sits inside the `/project` directory inside the container. Whilst this has been true for all Appsody Stacks so far, it may not be in the future.
An example of this is "Traditional WebSphere", where the standard docker images provide assets in `/work/config`.
This adds an optional `APPSODY_PROJECT_DIR` environment variable, which defaults to `/project`.

Add support for customizing the project directory

---

README.md

After we moved doc content under /website the link broke and resulted in a 404

Update readme code of conduct link

---

functest/init_test.go

Removed repository "experimental" so the CLI outputs that it could not find the stack, and the test passes if the CLI prints the correct message
Fixes: https://github.com/appsody/appsody/issues/199

cmd: fixed bug in appsody init test

---

cmd/build.go
cmd/dev_common.go
cmd/docker_commands.go
cmd/utils.go
functest/docker_options_test.go
functest/ports_test.go

Fixes #116 
Adds the --docker-options flag to allow users to send options to docker command (run, build) via the appsody command line.

--docker-options flag added

---

deploy-build/deploy.sh
docs-build/deploy.sh

Fixes #105 
Fixes #112 
Names created branches after the release version, not the travis build
Adds a message to say that website branch was not generated.

Added release version in branch names for website and .rb branch and also added  website release not created info message

---

Makefile

Fixes #98 
Also fixes PR 181
Addes logic to choose appsody version of controller if the controller is not present during functest.

added controller version and logic to pull controller for functest

---

cmd/build.go
cmd/dev_common.go

Bug for good path where -m=4g failed even though it was a valid docker-options parameter.
Retested on both good and bad path.
Fixes #203

regex fix for =

---

cmd/docker_commands.go

appsody build --dryrun segv's  same thing happens with appsody deploy --dryrun
Fixes #208

fix for wait on docker_commands dryrun path

---

cmd/dev_common.go
cmd/docker_commands.go
cmd/utils.go

Issue where /usr/local/Cellar/appsody/<release>/bin/appsody-controller did not exist, fixed error path to return error earlier.
Fixes #207

Fix checksum error path for controller copy

---

cmd/dev_common.go
cmd/docker_commands.go
cmd/operator.go
cmd/utils.go

Fixes #209 
Error when doing appsody install --dryrun
Note this PR needs to merge after 2 previous PRs, which will clean up extra files.

appsody operator install --dryrun causes error

---

cmd/deploy_delete.go

As discussed with @seabaylea @neeraj-laad and @tomleah - we felt it made more sense for `appsody delete` to be `appsody deploy delete`.  Otherwise it could be confusing as to what exactly is being deleted.  With `appsody deploy delete` it's clear that it's the deployment that's being deleted.
My first contribution - all feedback very welcome - hopefully this is correct.

Move delete cmd to subcmd under deploy

---

cmd/init.go

Temporary stop-gap for  #215, which we will leave open
Fixes #215
If there is a .appsody-config.yaml file we will never proceed regardless of --overwrite.
We will consider lifting these restrictions in a future sprint.

Added temporary help text for appsody init --overwrite

---

cmd/operator.go
cmd/root.go
cmd/utils.go

This changes the base URL used for the Appsody-operator to point to the latest release of the Appsody-operator repo.
It also makes it configurable via the `APPSODY_HOME/.appsody.yaml` file using a `operator: ` entry.
```
home: /Users/bailey/.appsody
images: index.docker.io
operator: https://raw.githubusercontent.com/appsody/appsody-operator/master/deploy/releases/0.1.0
```
The above example reverts to the current release URL (which are files embedded in master).

Switch operator download URL to latest release and make configurable

---

cmd/deploy.go
cmd/init.go

Fixes #220.
This is a critical fix, appsody deploy fails on windows without it.
The solution is to use the same cp logic for windows as the other os's.
Also I had to defer the remove of the temp file because it caused problems on windows.

Windows deploy fix

---

cmd/ps.go
functest/ps_test.go

Provide the option (along the lines of docker ps) to list details of the stack-based containers that are currently running in the docker environment.
Fixes: https://github.com/appsody/appsody/issues/69

Add ps command to list stack-based containers currently running

---

cmd/deploy.go
cmd/dev_common.go
cmd/extract.go
cmd/run.go
cmd/utils.go

Introduce a `--buildah` flag.
An alternate approach that addresses a drawback in https://github.com/appsody/appsody-docker/pull/9 - wherein static assumptions about the project structure was required.
Signed-off-by: Gireesh Punathil gpunathi@in.ibm.com
Still a work in progress, want to set the semantics straight before proposing.
cc @seabaylea - pls have a quick look and suggest!
cc @pushkarnk - pls feel free to add commit(s).

enable extract to use `buildah` sequences for image extraction

---

cmd/extract.go

When stacks whose Dockerfile defines less privileged users as the owner of the container, extraction fails in CRI-O deployments with:
```
[Debug] cp: cannot create regular file '/ex/Dockerfile': Permission denied
...
```
this is because the mount point /ex is owned by privileged user who started the parent container, and the less privileged user does not have write permission into it.
`chmod -R 666 /ex` or its ancestor folder prior to the mount does not seem to work it around.
So we go by the old bind mount route where:
- don't run the child container, just get its mount point,
- copy the project folder from the mount to the extract folder.

buildah: revert to the bind mount model for copying

---

cmd/extract.go

1. 
When stacks whose Dockerfile defines less privileged users
as the owner of the container, extraction fails in CRI-O
deployments because the mount point is owned by privileged
user who started the parent container, and the less privileged
user does not have write permission into it.
So we go by the old bind mount route where:
- don't run the child container, just get its mount point,
- copy the project folder from the mount to the extract folder.
2. 
A class of systems (e.g:- RHEL 7.6) exhibit situations wherein
the bindmount volumes are not propagated to the child containers
Accommodate those systems as well, by performing local copies
for the locations that are resident in the host.
ref: https://github.com/containers/buildah/issues/1821

buildah: use bind mount and localy copy

---

cmd/root.go
cmd/utils.go

Reads the users local appsody `repository.yaml` and switches the v1 index to use the v2 index.
fixes: https://github.com/appsody/appsody/issues/250

new index: switching index from v1 to v2

---

cmd/deploy.go

If the --knative flag is present and there is a app-deploy.yaml containing an appsodyapplication, the createKnativeService: true tag will be added to the yaml file.
If the --knative flag is not present and createKnativeService: true is in the app-deploy.yaml file the createKnativeService element will be removed.  if it is createKnativeService: false, it will remain.
If the stack does not contain an app-deploy.yaml file containing and appsodyapplication, the --knative flag will have no impact.
Unless the appsody deploy is done with a --tag, -t option the imagename will be prefixed with dev.local/<projectname>

Handle --knative option for current stacks as well as stacks that do not contain app-deploy.yaml

---

cmd/docker_commands.go
cmd/operator_utils.go
cmd/root.go
cmd/utils.go
functest/ports_test.go
functest/stop_test.go

Removed the "[" and "]" surrounding the args in the CLI output only in cases where output contains "docker command:" or "Running command:"
Fixes: #268

cmd: removed [] from argument list

---

cmd/dev_common.go
cmd/utils.go

Make this public so that tests can make use of it - for now, https://github.com/appsody/appsody/pull/314
We have a mind to refactor this function for re-usability; basically cache the image inspection data and reuse it for future calls, in the CLI life. To reduce clutter, one at a time!

cmd: export getEnvVar, to be reusable by tests

---

cmd/init.go

working directory was made configurable through `APPSODY_PROJECT_DIR`, but if that is exercised with any value other than `/project`, then `appsody init` fails at the moment. This is because of the hard-coding in the container startup command. Derive its value from
`getExtractDir()`

src: remove hard-coded reference to `/project`

---

cmd/dev_common.go

This PR adds a --no-watcher flag to disable file watching by the controller regardless of the Docker Environment variables in the stack.
In order for this PR to function correctly, a new release of the controller will be needed.
That function is part of Issue https://github.com/appsody/controller/issues/21 of the appsody controller component and its corresponding pull request.

added --no-watcher flag to disable file watching regardless of Stack Environment variable settings.

---

functest/extract_test.go

Extraction test logic:
~~Don't inspect the images, but just figure out the mount points from the debug log that is thrown out from extraction~~
- Get the environment variables from the images that was just extracted - GetEnvVar. Switch the current directory to meet the API's needs. (refactor it so that this isn't needed)
- For each mount that is a file, make sure the source and destination file sizes match.
- For each mount that is a folder, make sure the source and destination folders have same content (file name match)
- Skip mounts that were not extracted (e.g:- /mvn/...)
- For all cases, make sure we have a `Dockerfile` extracted at the vortex of the extraction.

test: add a test for `appsody extract`

---

functest/debug_test.go

Two improvements:
1. Right now the test is not waiting for the channel that
runs the goroutine for `appsody debug`, basically not checking
whether it was initiated / ran or not. Put up the container
check loop to make sure the container appears.
2. Name the container uniquely, deriving the name from the stack
so that back-to-back runs / turbulence in the test system do not
confuse the test logic - i.e., read and / or stop a wrong container.

test: wait for container to come up in debug test

---

cmd/list_test.go
cmd/repo_add_test.go

tests that would have run before this and crashed could leave the repo in a bad state - mostly leading to: "a repo with this name already exists." this is because the failed tests do not get a chance to run the cleanup routines which is supposed to remove the repo.
so clean it up pro-actively, ignore any errors. 
Helps in minimizing turbulence in test runs.

test: drain stale repo before adding

---

cmd/stack_lint.go
cmd/stack_yaml_lint.go

An extension to the directory linter that now validates the users `stack.yaml`
Validates:
- All fields are present
- Version is formatted as major.minor.patch
- Description length is limited to 70 characters
- Maintainer email has been provided as a point of contact
Fixes: https://github.com/appsody/appsody/issues/271

linter: added linting for stack.yaml

---

cmd/ps.go

Fixes: https://github.com/appsody/appsody/issues/357

cmd: print table only if non-empty

---

cmd/repo.go

While there is no platform-wide standard on the lengh of file path and / or www url, 120 proved to be too restrictive. Change to 1024 - should be a reasonable one. The table format gets skewed a bit with this, but data truncation on the other hand is more harmful, so!
Fixes: https://github.com/appsody/appsody/issues/350
cc @kylegc

repo: increase the table column width for repo

---

cmd/dev_common.go

1. Remove the 1 minute sleep in the runner
2. Adjust the messages accordingly.
Fixes: https://github.com/appsody/appsody/issues/334
cc @kylegc . It is not clear to me the need for `sleep`: In `tty` mode (ctrl+c intercepted by the controller) or not (ctrl+c intercepted by runner) , the `interrupt` signal is always obtained from the child (controller) , which means we don't need to wait anymore? Am I missing something? I tested in mac and linux, and did not see any issues with removal of sleep.

[on hold] cmd: remove sleep in runner when controller is interrupted

---

cmd/dev_common.go

~~Disallow anything that does not start with a `-`.
(luckily all the docker run options do)~~
EDIT: As per discussion, this was not pursued due to maintenance overhead.
Disallow `--help`
(not the best place to do `docker run --help`)
(in addition, even if it is, the output is truncated, so!)
Fixes: https://github.com/appsody/appsody/issues/346
cc @kylegc @chilanti @kewegner

cmd: harden `--docker-options` parsing

---

cmd/deploy.go
cmd/operator_uninstall.go
cmd/operator_utils.go

Fixes #376 
Fixes #371 
Can now detect env var in appsody-operator that uses valueFrom
Can handle Kabanero-operator created appsody-operators with multiple watchspaces.
Fixed two merge issues in deploy.go
namespace var not defaulted to "default"
config not correct, caused segv.

fix merge problems and check for multiple watch spaces, env var diffs

---

functest/init_test.go

We updated the nodejs-express template from `skaffold` to `scaffold`, and the test had not been updated. This is currently failing in multiple PRs on the Linux builds, since we only run functional tests on Linux.

Fix scaffold test

---

cmd/root.go
cmd/utils.go

Motivation:
Commands may call getEnvVar() multiple times for different environment
variable names. Every invocation needs a `docker inspect` invocation followed
by unmarshalling of the json and a walk through the resulting array. Caching
the environment variables in a map can avoid repeating these steps and speed-up
command execution.

Cache and reuse the results of getEnvVar()

---

cmd/stack_validate.go

adding this for stacks like python-flask that use the watcher during `test` which cause `test` to not return which causes `appsody stack validate` to hang forever

added --no-watcher to appsody test

---

functest/ports_test.go

Previously this test was not properly checking the output. The input syntax was incorrect but the test always passed. I've fixed this with a regex

Fix docker options test

---

functest/ps_test.go

We don't need to wait so long for this test. 30 seconds is plenty of time for the container to be up.

Decrease wait for ps test

---

cmd/cmdtest/testutils.go
cmd/root.go
functest/extract_test.go

Fix testutils RunAppsodyCmd so it doesn't use os.Args or os.Getwd

---

cmd/init.go
cmd/root.go
cmd/utils.go
cmd/utils_test.go

Fixes #287 
Removed projectName from RootCommandConfig and use ProjectConfig.ProjectName instead
Removed setProjectName func and instead created a simpler saveProjectNameToConfig func
Simplify getProjectName

Refactor project name

---

cmd/utils.go

It looks like #375 broke the ability to set an alternative image repo for the stack images by setting `projectConfig.Stack = stack` after it has been updated with the config.
This PR moves this to before the custom config, allowing the config to override the default.

Fix regression that prevents config of alternative stack repositories

---

cmd/docker_commands.go
cmd/init.go
cmd/testdata/default_repository_config/config.yaml
cmd/testdata/empty_repository_config/config.yaml
cmd/testdata/multiple_repository_config/config.yaml
cmd/utils.go
cmd/utils_test.go
functest/docker_commands_test.go
functest/test_test.go

Corrected instances where only stdErr was being propagated as an exit message to instead return stdOut along with stdErr.
Fixes: #462

Standardised most of the error propagation in utils.go

---

cmd/build.go

`dev.appsody.image.commit` labels will be added to the stack, and we need to make sure to transfer them to the appsody project as a different label, such as `dev.appsody.stack.commit`

Transfer stack commit labels properly

---

cmd/stack_lint.go

The stack name should be restricted, especially now that it is going into k8s labels

Enforce stack dir name (stack id) with the project name rules

---

cmd/stack_validate.go

The stack validate build command should be using a temporary project name, not the stack name for the image tag.

Set better image name for stack validate build test

---

cmd/utils.go
cmd/utils_test.go

* Print the version update message to Stderr (this means that scripts can read only from stdout when parsing JSON from the `-o json` flag)
* Reformat the `doVersionCheck` function so that minimal upkeep is needed if the message is changed in common parts and added `GetUpdateString` function.
Manually tested.
Written unit tests for `GetUpdateString` function to test different output depending on OS.
The only catch with using `Warning.logf` instead of `Info.logf` is the `[Warning]` that is printed before the version message so the output for MacOS is now:
```
[Warning] 
*
*
*
A new CLI update is available.
Please run `brew upgrade appsody` to upgrade from vlatest --> 0.4.10.
*
*
*
```
@kylegc FYI.
Signed-off-by: James Wallis <james.wallis1@ibm.com>

Output version update message to Warning

---

.gitignore
Makefile

Fixes #493 
This isn't pretty, but it was something I had created previously and used locally for myself.
It prints live updates of the current test being run and its PASS/FAIL status, then at the end prints the detailed output only for the failed tests.

Improve test output to only show detail on failures

---

cmd/repo_add.go
cmd/repo_list.go
cmd/repo_remove.go
cmd/repo_set_default.go

Changed help text formatting for following `appsody stack` commands:
- `appsody repo add`
- `appsody repo list`
- `appsody repo remove`
- `appsody repo set-default`
Fixes: #583

appsody repo: reformat help text

---

cmd/list.go
cmd/utils.go

Changed help text formatting for `appsody list` command
Fixes: #580

appsody list: reformat help text

---

cmd/debug.go

Changed help text formatting for `appsody debug` command
Fixes: #576

appsody debug: reformat help text

---

Makefile

The second `-ldflags` arg overwrote the first so the VERSION wasn't getting set. Fixed it by setting both flags in the same `-ldflags` option.

Fix version issue because only one -ldflags is allowed

---

cmd/stack_package.go

Currently, when running `appsody stack package`, the `language` field in the generated index puts the value for the `license` field. This PR fixes this.
Fixes: https://github.com/appsody/appsody/issues/663

cmd: Fix stack package so that the correct value for language is put in the index

---

cmd/cmdtest/testutils.go

This PR creates a skeleton appsody home directory based on the name of the currently executing test, and uses this for all commands run via `testutils.RunAppsodyCmd`.
Resolves #491 
~Work-in-progress:  this needs rebasing once https://github.com/appsody/appsody/pull/639 is merged.~

Sandbox tests in their own home directory

---

cmd/build.go

In other words - only override exisiting appsody labels and annotations in app-deploy
For `kNative` and `ApplicaitionImage` the behaviour can be specified through command line flags to the deploy command.

Do not override existing non-appsody labels and annotations in app-deploy

---

cmd/utils.go
cmd/utils_test.go

Continue when we don't get the version instead of exiting routine.

Fix error message to print string of outbuffer instead of the buffer.

---

cmd/init.go
cmd/root.go

@upLukeWeston @Kamran64 We should avoid using os.Exit() wherever possible and return errors instead.

Remove some os.Exit()s

---

cmd/build.go
cmd/cmdtest/testutils.go
cmd/root.go
cmd/utils.go
functest/build_test.go

Currently the `created` label from the image build and the `app-deploy.yaml` are not matching because we compute the labels twice. In this PR, I cache the labels inside the `RootCommandConfig`. I thought of packaging up the labels into a struct, but it could be the case that a function will be used independently - would like to hear thoughts on this!

Ensure consistent labels in image and app-deploy

---

functest/build_test.go

We hit a weird situation where the local commit had a single quote in it, and this test was failing because it removed all the quotes. It should only remove the leading and trailing quotes.

Only remove quotes and newlines from beginning and end of inspect output

---

cmd/git_utils.go
functest/build_test.go
functest/deploy_test.go

Although not yet supported by the command line options, all of our code runs relative to an absolute path ProjectDir instead of the current working directory - except for the git commands. This should be fixed for tests to run properly and future proof the code for command line support.

Run git commands in project dir rather than the current working directory

---

functest/debug_test.go
functest/ps_test.go
functest/run_test.go
functest/stop_test.go
functest/test_test.go

Another strange error we were hitting running the tests locally:
`panic: Log in goroutine after TestRun has completed`
It turns out that the goroutine calling appsody wasn't finished and continued to log messages with t.Log() after the tests had been completed. The go test framework panics when this happens.
This seems to only happen when running the tests individually, not as the whole test bucket, but I'm guessing that was just lucky timing. I've fixed the problem by waiting for data on the goroutine channel before finishing the test.

Fix tests from panicing locally from log after test completed

---

cmd/build.go
cmd/init.go
cmd/stack_package.go
cmd/stack_package_test.go
cmd/stack_validate.go
cmd/utils.go

The `stack package` and `validate` command now uses `registry/namespace/stack:0.0.0` format to fully qualify the stack location. This is embedded into the template `.appsody-config.yaml` files.
Added a flag so user can change the default registry.
Fixes: #669 
This PR should wait for https://github.com/appsody/appsody/pull/725 and https://github.com/appsody/appsody/pull/749

package/validate: image registry flag

---

cmd/stack_package.go
cmd/stack_package_test.go

This is not a breaking change to existing stacks using templating.  This is a temporary solution due to many errors happening with the new templating feature.  This means that it will avoid code collisions from other templating libraries that use `{{` `}}` as delimiters, as the new delimiters are `{{.stack` `}}`.

Change templating delimiters to use {{.stack}}

---

cmd/stack_validate.go
cmd/stack_validate_utils.go

Propagate the verbose option through to appsody command execution during stack validate.
Fixes #814

Propagate stack package verbose option

---

cmd/stack_create.go

Changes behaviour of `appsody stack create` to use the `incubator/starter` stack instead of the `sample/starter`  as it is a valid, functioning stack.  Fixes issue: #832

Appsody stack create now uses incubator/starter

---

cmd/deploy.go
cmd/operator_install.go
cmd/operator_utils.go
functest/deploy_test.go

Fixes: https://github.com/appsody/appsody/issues/813
Adds a new flag, `no-check` to `appsody deploy` and `appsody operator install` to suppress `kubectl get pods --all-namespaces` when checking if an operator already exists in the namespace.
Instead only the namespace specified will be queried (In case permission issues occur with `all-namespaces` mentioned in the issue above)
- Opening as draft so that I can write tests

Add a no-check flag to to suppress all-namespaces kubectl command

---

cmd/init.go
cmd/utils.go

When running `appsody init dev.local/java-microprofile` or init on any stack with a non-docker.io stack image, the init process will incorrectly pull and extract the docker.io image.
This bug was introduced in appsody 0.5.5 when adding --stack-registry to init
As a workaround you can specify `--stack-registry dev.local` on the init command.

Make sure to set the stack registry to the one in the config file on init's extract

---

Makefile
cmd/stack_create_test.go
functest/create_test.go
functest/run_test.go

Due to change from `stack create` this test was failing and as a result blocking us from putting through any PR's.  This PR removes that test and I will relook these tests in PR #884 and refactor them.

Removed InvalidStackCase2 test

---

Makefile
cmd/cmdtest/testutils.go
cmd/stack_create_test.go
cmd/stack_package_test.go
functest/build_test.go
functest/create_test.go
functest/debug_test.go
functest/deploy_test.go
functest/extract_test.go
functest/package_test.go
functest/run_test.go
functest/test_test.go

* Set `stacksList` to be `incubator/nodejs` if `$STACKS_LIST` is empty, rather than skipping over the tests (in various test files) - closes #888 .
* Removed loggingConfig initialisations from cases where they are no longer necessary.
* Removed `RemoveAll()` cases from tests as they're no longer necessary due to Sandboxing.
* Changed the tests in `stack_package_test.go` to be in tables to reduce repeated code.

Cleaned up some of the testing codebase

---

functest/operator_install_test.go

- These tests can only be run locally as travis currently does not support kube commands.
Fixes: #731 
Fixes: #732 
Fixes: #733

operator commands: Improve code coverage

---

cmd/git_utils.go
cmd/git_utils_test.go

Bumps code coverage of `git_utils.go` from 80% to 91%
I had to capitalise some functions to export them for testing
Fixes: #717

git_utils.go: improve code coverage

---

cmd/cmdtest/testutils.go

Added docker volumes clean up to the sandbox cleanup function
Fixes: #685

testutils.go: clean up docker volumes created by tests

---

cmd/build.go
functest/build_test.go

Convert `app.appsody.dev/name` label to `app.kubernetes.io/part-of` for the Kubernetes resource.

Adding support for kubernetes part-of label

---

cmd/operator_utils.go

With an (inadvertent) bad config (before this):
% appsody version; appsody operator install
appsody 0.5.8
Attempting to get resource from Kubernetes ...
Running command: kubectl get deployments -o=jsonpath='{.items[?(@.metadata.name=="appsody-operator")].metadata.namespace}' -n default
[Error] kubectl command failed:
%
This isn't so helpful, kubectl reports useful diagnostics to stderr
(after this):
% ./build/appsody-0.0.0-linux-amd64 operator install
Attempting to get resource from Kubernetes ...
Running command: kubectl get deployments "-o=jsonpath='{.items[?(@.metadata.name==\"appsody-operator\")].metadata.namespace}'" -n default
[Error] kubectl command failed: Unable to connect to the server: x509: certificate signed by unknown authority

Report stderr when kubectl fails

---

cmd/utils.go

Not only Dirs, symlinks as well don't have data to copy, and trying causes
[Debug] source is: /home/sam/w/cloud/appsody-stacks/incubator/nodejs-kafka
[Debug] filename is: source
[Debug] target is: /home/sam/.appsody/stacks/dev.local/nodejs-kafka.v0.4.3.
[Info] source archive file created at : /home/sam/.appsody/stacks/dev.local/nodejs-kafka.v0.4.3.source.tar.gz
[Error] Error trying to tar: archive/tar: write too long
Also, wrap errors so that they can be traced to their source.

Only attempt to copy tar data for regular files

---

cmd/build.go
cmd/deploy.go
cmd/dev_common.go
cmd/init.go
cmd/stack_lint.go
cmd/stack_package.go
cmd/utils.go

When running an appsody command with verbose, cobra creates flags before it knows which command to run, this leads to many repeated logs. The only way (I know) to avoid this, is to avoid creating logs inside the flag initialisation and to bring them outside the `addStackRegistryFlag()` function
Fixes: #882

flags: remove logs from initialising stack registry flag

---

.travis.yml
cmd/stack_create_test.go
cmd/utils.go

To increase the number of http request on travis we add a `GH_READ_TOKEN` env.

Adding read-only token and commenting old stack create tests

---

cmd/init.go
cmd/utils.go
functest/init_test.go

Cleanup unused docker volumes during init.
This should be rebased on top of https://github.com/appsody/appsody/pull/946, once it goes into master.
Fixes: #926

init: cleanup unused docker volumes

---

cmd/dev_common.go
cmd/docker_commands.go
cmd/utils.go
functest/docker_options_test.go
functest/run_test.go

Allow user specified mounts in `appsody <run|debug|test> --docker-options`, but throw an error if the user mount interferes with the stack mounts
This should be rebased on top of #946, once it goes into master.
Fixes: #509

[WIP] dev_common.go: allow user specified mounts

---

cmd/utils.go

Adds the digest of the image as a label (only if the image actually has one)
Fixes: https://github.com/appsody/appsody/issues/957

Add image digest as a label

---

cmd/stack_package.go
cmd/utils.go

Indicate this by appending a new field `deprecated: reason` and prepending `[Deprecated] ` to the displayName field in the Codewind json if the stack is deprecated
Sample `appsody stack package` output: 
```
{
"displayName": "[Deprecated] Local Node.js simple template",
"description": "Runtime for Node.js applications",
"language": "nodejs",
"projectType": "appsodyExtension",
"projectStyle": "Appsody",
"location": "file:///Users/sandy.koh@ibm.com/.appsody/stacks/dev.local/nodejs.v0.3.5.templates.simple.tar.gz",
"links": {
"self": "/devfiles/nodejs/devfile.yaml"
},
"deprecated": "65/65/65 - for some reason"
}
```
Fixes: #983

indicate a deprecated stack in the generated codewind index

---

cmd/git_utils.go
cmd/stack_package.go
cmd/stack_package_test.go
cmd/utils.go
functest/build_test.go
functest/stack_package_test.go

Pair programmed with @CameronMcWilliam!
Removed the following labels/annotations being added to the stack image/`app-deploy.yaml`:
- `dev.appsody.image.commit.author` 
- `dev.appsody.image.commit.committer`
- `dev.appsody.stack.authors`
- `dev.appsody.stack.commit.author`
- `dev.appsody.stack.commit.committer`
-  `org.opencontainers.image.authors`
Fixes: #987

remove personal data from stack image labels and annotations

---

cmd/cmdtest/testutils.go
cmd/dev_common.go
cmd/utils.go

- Extended from https://github.com/appsody/appsody/pull/994 as it enables an `APPSODY_DEBUG_PORT` variable to detect debug ports.
- This PR allows `appsody debug` and `appsody test` to be run when using `APPSODY_K8S_EXPERIMENTAL`. Previously we weren't propagating the `mode` variable to this block and therefore the controller would always fall back to using the `appsody run` command.
- Note: For Codewind, they only actually need `appsody debug` at this time but due to the nature of the code, both `appsody test` and `appsody debug` will be supported since we're passing the arg to the controller. @makandre - Should we block invocations of `appsody test` when running in Codewind or do you think it will be fine to support both?
YAML structure in `app-deploy.yaml`:
```
- name: …
```

Enable other appsody "modes" in appsody k8s and stop exposing the debug port for Codewind

---

cmd/stack_lint_dockerfile_stack.go
cmd/stack_lint_test.go
cmd/stack_yaml_lint.go

Makes `appsody stack lint` much more forgiving. It will no longer error out for missing variables in the `Dockerfile-stack`. This has caused problems for stacks that inherit from a parent failing due to missing variables. It also changes the license checker to a warning too.
Fixes: https://github.com/appsody/appsody/issues/995
Fixes: https://github.com/appsody/appsody/issues/996

Make appsody stack lint more forgiving

---

cmd/stack_lint_dockerfile_stack.go

Adds the `APPSODY_DEBUG_PORT` variable to the linter as a warning.

Lint APPSODY_DEBUG_PORT environment variable

---

cmd/utils.go

The current code to extract and check the minimum docker version is unsafe, since it assumes that the version is the first x.y.z sequence to appear in the output of the `docker version` command. This is no longer true, for instance with docker 19.03.12 on macOS (where the first version listed in the output turns our to be the Azure integration version!). This causes all `appsody init` commands to fail if the stack in question specifies a minimal Docker version in its stack.yaml.
While there is perhaps a larger conversation to be had about whether the correct goal is to check the client or server version of docker (or both?), this fix simply makes the current attempt to check the docker client version safe.
Fixes #1008

Use format option to extract docker version
