appsody/appsody

cmd/completion.go
cmd/debug.go
cmd/deploy.go
cmd/docs.go
cmd/extract.go
cmd/init.go
cmd/list.go
cmd/repo_add.go
cmd/repo_list.go
cmd/repo_remove.go
cmd/root.go
cmd/run.go
cmd/stop.go
cmd/test.go
cmd/version.go

We are responding to Helen's requested changes in the earlier PR.

renames for cli doc generation

---

cmd/testdata/default_repository_config/repository/repository.yaml
cmd/testdata/index.yaml
cmd/testdata/multiple_repository_config/repository/repository.yaml

Signed-off-by: Kyle G. Christianson <christik@us.ibm.com>

Update the test code index.yaml so they dont link back to old images

---

Makefile

Switched from pulling from personal Docker account to appsody org.

Pulls debian builder from appsody Docker org.

---

docs-build/deploy.sh

This satisfies the work for #56 
The script was modified to point to the appsody/website repo.

change repo to appsody website

---

cmd/repo.go
cmd/repo_add.go

Ensure valid and unique repo names

---

.travis.yml
RELEASE.md

Release docs

---

cmd/dev_common.go
cmd/stop.go

More detail for appsody stop help text.

---

cmd/docs.go

Remove title and section from header in generated cli-commands.md

---

cmd/docs.go
cmd/list.go
cmd/repo_remove.go
cmd/repo_remove_test.go

Partial fulfillment of #36 
Removed os.exit from list.go and docs.go

Remove os exit from docs and list #3

---

cmd/init.go

Removed os.exit(1) from init.go which will aid in automated testing.

remove os.exit from init.go

---

cmd/dev_common.go
cmd/docker_commands.go
cmd/init.go
cmd/operator.go
cmd/utils.go

Fixes #213 
@chilanti @neeraj-laad have a look at this too.  Making @tnixa the reviewer.
The file of interest is init.go
Note: merge in after previous PRs.
@tnixa and I will do more testing of the PR in the AM.

Check for bad template name for v1 repos for appsody init v1/stack templatename

---

cmd/operator_install.go
cmd/operator_utils.go

Clean up enhancements for operator install

---

cmd/deploy.go
cmd/init.go
deploy-build/deploy.sh
docs-build/deploy.sh

Fixes #231
Changes branch name to testTRAVIS_TAGTRAVIS_BUILD_NUMBER

Branch name fix during travis build.

---

cmd/utils.go

Added "connected to Internet" safeguarding check to "latest version" check
Partially solves: #265

cmd: added wifi safeguarding to version check

---

cmd/extract.go

Reverts appsody/appsody#280
@gireeshpunathil  - I didn't see the message - reverting this PR.

Revert "buildah: revert to the bind mount model for copying"

---

cmd/dev_common.go

Fixes: https://github.com/appsody/appsody/issues/102
cc @kylegc  @kewegner @neeraj-laad

run: propagate verbose flag to the controller

---

cmd/extract.go

Ref: https://github.com/appsody/appsody/issues/174
cc @neeraj-laad @tnixa

extract: don't suppress underlying error messages

---

.travis.yml
deploy-build/deploy.sh
docs-build/deploy.sh

- Switching the GitHub tokens 
Once this is in we should change the token in Travis settings

build: switch user to appsody-devops

---

cmd/root.go
functest/ports_test.go
functest/stop_test.go

Remove the code (PR #273 ) which removed "[]" from the output.
That issue will be dealt with in another issue/pull request.

temporary fix to restore [] in output

---

docs/testing/deploy_knative_istio_test_notes.md
docs/testing/init_list_docker-options_test_notes.md
docs/testing/operator_test_plan_v3.md
docs/testing/repo_init__list_test_notes.md
docs/testing/tekton_test_notes.md

store testing docs and notes in /docs/testing

testing docs

---

cmd/repo.go

Fixes: https://github.com/appsody/appsody/issues/309
cc @neeraj-laad

cmd: highlight default repo in `appsody list`

---

cmd/deploy.go
cmd/deploy_delete.go
cmd/dev_common.go
cmd/extract.go
cmd/init.go
cmd/operator.go
cmd/stack_lint.go
cmd/utils.go

Refs: https://github.com/appsody/appsody/pull/314
cc @chilanti

utils: export exists

---

cmd/dev_common.go
cmd/docker_commands.go
cmd/root.go

Support TTY interactive mode

---

cmd/utils.go

cmd: limited calls to check latest version available

---

cmd/deploy.go

Fixes  #340
You can now change metadata: Name and the deploy will recognize it and search for the correct deployment URL.

Tolerate deployment name change in app-deploy.yaml

---

cmd/utils.go

Fixes: https://github.com/appsody/appsody/issues/115

utils: additional verbosity for pull|push commands

---

cmd/utils.go

Reverts appsody/appsody#339
Sorry guys, but I'm reverting this for a better fix.

Revert "utils: additional verbosity for pull|push commands"

---

cmd/utils.go

Set docker pull commands to log INFO

---

docs/testing/operator_test_plan_v3.md

Handle the case of valueFrom for WATCH_NAMESPACE
Handle the case where WATCH_NAMESPACE is a comma separated list.

Add new documentation scenarios for  operator and deploy 

---

cmd/stack_package.go
cmd/stack_validate.go

These are the changes stemming from the website pull request comments

validate and package command help changes

---

cmd/init.go

Use full filepaths in init

---

cmd/cmdtest/testutils.go
cmd/list.go
cmd/list_test.go
cmd/repo.go
cmd/repo_list.go
cmd/repo_list_test.go
cmd/testdata/multiple_repository_config/config.yaml
cmd/testdata/multiple_repository_config/repository/repository.yaml
vendor/gopkg.in/yaml.v2/go.mod
vendor/gopkg.in/yaml.v2/go.sum

Inspired from #230 
Fixes #53 
I think the tests can be better... Let me know what you think @kylegc

Adding machine output for list and repo list commands

---

cmd/stack_lint_test.go
functest/build_test.go
functest/debug_test.go
functest/deploy_test.go
functest/docker_options_test.go
functest/extract_test.go
functest/init_test.go
functest/ports_test.go
functest/ps_test.go
functest/run_test.go
functest/stop_test.go
functest/test_test.go

Use t.Log where possible in testing

---

cmd/stack_package.go
cmd/stack_validate.go

This fixes issues #444 and #396

appsody stack package updates

---

functest/test_test.go

Previously this test was not waiting for the command to finish and checking for errors, it was always immediately successfully passing the test.

Add wait for test test to complete

---

cmd/build.go
cmd/deploy.go
cmd/dev_common.go
cmd/docker_commands.go
cmd/extract.go
cmd/git_utils.go
cmd/init.go
cmd/repo.go
cmd/root.go
cmd/stack_package.go
cmd/testdata/.appsody-config.yaml
cmd/utils.go
functest/build_test.go
vendor/github.com/spf13/viper/go.mod

Adding labels to final docker image

Adding Labels to final 

---

cmd/docker_commands.go
cmd/init.go
cmd/utils.go
functest/stop_test.go

Remove os.Getwd() from defaultProjectName() and temp code from test

---

cmd/stack_create.go

Extract folder check added

---

cmd/build.go
cmd/stack_package.go
cmd/utils.go

Add standard labels to stack image on package

---

cmd/stack_create.go

fixes: https://github.com/appsody/appsody/issues/481

Stack Create Command Dryrun Error Fixed

---

cmd/stack_lint.go

Updated help text for `appsody stack lint` command
Signed-off-by: Neeraj Laad <neeraj.laad@gmail.com>

doc: help text change for stack lint command

---

cmd/root.go

Fix problem where root flags are ignored at the end of command

---

cmd/stack_package.go

Only run docker build once per appsody stack package

---

cmd/stack_package.go

Make stack github urls labels drill down to specific stack

---

cmd/build.go
cmd/utils.go
cmd/utils_test.go

Fixes https://github.com/appsody/stacks/issues/460

Extra validation when converting labels to kubernetes

---

cmd/git_utils.go
cmd/utils.go

Moved trimming trailing upstream information to git_utils.go from utils.go

---

cmd/stack_validate.go

Set pull policy IFNOTPRESENT for stack validate command

---

cmd/stack_package.go
cmd/stack_validate.go

Add new image-namespace argument and use value when building
Signed-off-by: Steve Groeger GROEGES@uk.ibm.com

Add new image-namespace argument and use value when building

---

cmd/stack.go
cmd/stack_addtorepo.go
cmd/stack_package.go

Create the `appsody stack add-to-repo` command

---

cmd/repo.go
cmd/stack_package.go

Adjusts `stack package` so that requirements specified in the `stack.yaml` are added to the index.
Fixes: https://github.com/appsody/appsody/issues/659

Adjust stack package so that requirements set are added to dev local indexes.

---

cmd/repo_add.go

Make example for 'appsody repo add' command more concise.
Related to: https://github.com/appsody/appsody/issues/683

appsody repo add: refactor help text

---

cmd/stack_addtorepo.go

Fix issue with opening a repository index file referenced with file:/// 

---

cmd/deploy.go

`config.nobuild` or `config.build`?

Add no-build flag to deploy and convert generate-only to just build

---

cmd/build.go
cmd/git_utils.go
cmd/stack_package.go

Hide the stack trace on git errors and improve the log message

---

cmd/utils.go

utils: Dont use docker.io when checking if local image exists

---

cmd/utils.go

The travis builds started failing on the appsody version check because the command "appsody" was not found on the path. Appsody is obviously running, but was not installed on the path. I modified the version checker to specially handle "appsody" and use the currently running VERSION which we already know if the code.
I also improved the logging messages and flattened the code.

Fix appsody version check failure when appsody is not on the path

---

cmd/stack_yaml_lint.go

- Update the linter to check that stack requirements meet the format of the package we use to set constraints.
Fixes: https://github.com/appsody/appsody/issues/779

Update the linter to check for stack requirements

---

cmd/build.go
cmd/stack_package.go
cmd/stack_yaml_lint.go
cmd/utils.go

Fixes: https://github.com/appsody/appsody/issues/768

Added wifi safeguarding to license check

---

Makefile
build.md

Improve the docs on building the CLI locally (and enhance the make file to make to easier to get a copy of your build CLI).
Partially Fixes: #177

Better description and additional makefile support

---

cmd/repo.go
cmd/utils.go

Ensure docker.io on inspect and write to .appsody.yaml

---

cmd/stack_validate.go

Chmod the temporary directory for init to use to be 0777

---

cmd/root.go

Refactor global flags definitions as part of https://github.com/appsody/appsody/issues/463

refactor global flags definitions

---

cmd/stack.go
cmd/stack_removefromrepo.go

Update to add remove-from-repo command

---

cmd/cmdtest/testutils.go
cmd/list_test.go
cmd/repo_add_test.go
cmd/repo_list_test.go
cmd/repo_remove_test.go
cmd/repo_set_default_test.go
cmd/utils_test.go
functest/docker_commands_test.go
functest/init_test.go
functest/testdata/bad_format_repository_config/config.yaml
functest/testdata/bad_repo_url_repository_config/config.yaml
functest/testdata/empty_repository_config/config.yaml

Fix build failures by setting up the sandbox and sub-tests properly for parallel testing

---

cmd/stack_validate.go

create temp dir in .appsody

---

cmd/cmdtest/testutils.go

Fix truncating of test output by using an in-memory pipe and waiting before closing the reader

---

build.md

- Remove future tense
- Split long sentences
- Tidied up wording

Edit building from source instructions

---

.travis.yml
cmd/build.go
cmd/stack_package.go
functest/package_test.go

Added Buildah tests for stack package

---

cmd/build.go
cmd/deploy.go
functest/build_test.go
functest/deploy_test.go

Fix namespace issue

---

cmd/extract.go

Fix buildah extract

---

cmd/build.go
cmd/deploy.go
functest/build_test.go

Do not set createKnativeService in app-deploy.yaml if knative flag is not present

---

.travis.yml
functest/extract_test.go

Fixes: https://github.com/appsody/appsody/issues/726

Tests for extract.go

---

cmd/build.go
cmd/stack_package.go
cmd/utils.go
cmd/utils_test.go
functest/docker_options_test.go

Fix build options

---

cmd/stack_package.go
cmd/utils.go

Add `link` element to JSON file
Fixes: #954

fix JSON file format

---

.travis.yml

Added token to Travis settings.

Remove token from .travis.yml

---

cmd/deploy.go
cmd/utils.go
cmd/utils_test.go

Signed-off-by: Steven Groeger <groeges@uk.ibm.com>

Add code to get correct application URL when running on IBM Cloud systems

---

cmd/dev_common.go

Fixes: https://github.com/appsody/appsody/issues/932

Stop appending -dev to container name

---

cmd/utils.go

Revert "Add image digest as a label"

---

cmd/build.go
cmd/extract.go
cmd/utils.go
functest/build_test.go

Adds a label for the digest of the image being pulled down.
Fixes: https://github.com/appsody/appsody/issues/957

Add label for image digest

---

cmd/dev_common.go
cmd/utils.go

Reimplements some of the debug port changes for Codewind as there were random failures for stacks with multiple ports exposed.
Fixes: https://github.com/appsody/appsody/issues/1002

Codewind debug port fixes
